
CREATE TABLE BOOKS_AUD (
                           EVENT_ID INT(11) NOT NULL AUTO_INCREMENT,
                           EVENT_DATE DATETIME NOT NULL,
                           EVENT_TYPE VARCHAR(10) DEFAULT NULL,
                           BOOK_ID INT(11) NOT NULL,
                           OLD_TITLE VARCHAR (40),
                           NEW_TITLE VARCHAR (40),
                           OLD_PUBYEAR INT(4),
                           NEW_PUBYEAR INT(4),
                           PRIMARY KEY (EVENT_ID)
);

CREATE TABLE READERS_AUD (
                             EVENT_ID INT(11) NOT NULL AUTO_INCREMENT,
                             EVENT_DATE DATETIME NOT NULL,
                             EVENT_TYPE VARCHAR(10) DEFAULT NULL,
                             READER_ID INT(11) NOT NULL,
                             OLD_FIRST_NAME VARCHAR (255),
                             NEW_FIRST_NAME VARCHAR (255),
                             OLD_LAST_NAME VARCHAR (255),
                             NEW_LAST_NAME VARCHAR (255),
                             OLD_PESEL_ID VARCHAR (20),
                             NEW_PESEL_ID VARCHAR (20),
                             PRIMARY KEY (EVENT_ID)
);

-- TRIGGERS AFTER INSERT

DELIMITER $$
CREATE TRIGGER READER_INSERT AFTER INSERT ON READERS
    FOR EACH ROW
BEGIN
    INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID, NEW_FIRST_NAME, NEW_LAST_NAME, NEW_PESEL_ID)
    VALUES(CURTIME(), "INSERT", NEW.READER_ID, NEW.FIRST_NAME, NEW.LAST_NAME, NEW.PESEL_ID);
END $$

DELIMITER ;

DELIMITER $$
CREATE TRIGGER BOOK_INSERT AFTER INSERT ON BOOKS
    FOR EACH ROW
BEGIN
    INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, NEW_TITLE, NEW_PUBYEAR)
    VALUES(CURTIME(), "INSERT", NEW.BOOK_ID, NEW.TITLE, NEW.PUBYEAR);
END $$

DELIMITER ;


-- TRIGGERS AFTER DELETE

DELIMITER $$

CREATE TRIGGER READER_DELETE AFTER DELETE ON READERS
    FOR EACH ROW

BEGIN
    INSERT INTO readers_aud (EVENT_DATE, EVENT_TYPE, READER_ID)
    VALUES (CURTIME(), "DELETE", OLD.READER_ID);
END $$

DELIMITER ;

DELIMITER $$

CREATE TRIGGER BOOK_DELETE AFTER DELETE ON BOOKS
    FOR EACH ROW

BEGIN
    INSERT INTO books_aud (EVENT_DATE, EVENT_TYPE, BOOK_ID)
    VALUES (CURTIME(), "DELETE", OLD.BOOK_ID);
END $$

DELIMITER ;


-- TRIGGERS AFTER UPDATE

DELIMITER $$

CREATE TRIGGER BOOK_UPDATE AFTER UPDATE ON BOOKS
    FOR EACH ROW
BEGIN
    INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, NEW_TITLE, NEW_PUBYEAR,
                           OLD_TITLE, OLD_PUBYEAR)
    VALUES (CURTIME(), "UPDATE", OLD.BOOK_ID, NEW.TITLE, NEW.PUBYEAR,
            OLD.TITLE, OLD.PUBYEAR);
END $$

DELIMITER ;


DELIMITER $$

CREATE TRIGGER READER_UPDATE AFTER UPDATE ON READERS
    FOR EACH ROW
BEGIN
    INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID, NEW_FIRST_NAME, NEW_LAST_NAME, NEW_PESEL_ID,
                             OLD_FIRST_NAME, OLD_LAST_NAME, OLD_PESEL_ID)
    VALUES (CURTIME(), "UPDATE", OLD.READER_ID, NEW.FIRST_NAME, NEW.LAST_NAME, NEW.PESEL_ID,
            OLD.FIRST_NAME, OLD.LAST_NAME, OLD.PESEL_ID);
END $$

DELIMITER ;


