CREATE TABLE STATS (
					STAT_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
                    STAT_DATE DATETIME NOT NULL,
                    STAT VARCHAR(20) NOT NULL,
                    VALUE INT(11) NOT NULL
                    );

CREATE VIEW BESTSELLERS_COUNT AS
SELECT COUNT(*) AS TOTAL_BESTSELLERS
  FROM BOOKS
 WHERE BESTSELLER = 1;

  DELIMITER $$

 CREATE EVENT UPDATE_BESTSELLERS_STATS
 	ON SCHEDULE EVERY 1 MINUTE
     DO
 		 BEGIN
 		 	CALL UpdateBestsellers();
 			INSERT INTO STATS (STAT_DATE, STAT, VALUE)
             SELECT CURDATE(), "BESTSELLERS", TOTAL_BESTSELLERS
             FROM BESTSELLERS_COUNT;
 		 END $$

  DELIMITER ;
